### ISSUE TITLE
how can i use this

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracoui#7]
hey is there any tutorial how can i use this UI?

**Comment by niicojs** [comment]
Just browse the url given to you by dracowalker

**Comment by Nackenschelle** [comment]
is it the same UI or have this ui more features?

**Comment by niicojs** [comment]
This is what you get when you go to the link the walker give you.

**Comment by Nackenschelle** [comment]
thanks buddy
can be closed
